import os

from app_config.settings.base import BaseSettings, _env_bool, _env_float, _env_int, _env_str


class AiAutomationSettings:
    OPENAI_API_KEY = _env_str("OPENAI_API_KEY", "")
    LLM_DEFAULT_MODEL = _env_str("LLM_DEFAULT_MODEL", "gpt-4o-mini")

    MATCH_DATASET_ENABLED = _env_bool("MATCH_DATASET_ENABLED", False)
    MATCH_DATASET_PATH = _env_str("MATCH_DATASET_PATH", "")
    MATCH_DATASET_MAX_BYTES = _env_int("MATCH_DATASET_MAX_BYTES", 0)

    PDF_TEXT_CACHE_DIR = _env_str(
        "PDF_TEXT_CACHE_DIR", os.path.join(BaseSettings.BASE_DIR, "data", "pdf_text_cache")
    )
    PDF_TEXT_CACHE_ENABLED = _env_bool("PDF_TEXT_CACHE_ENABLED", True)
    PDF_TEXT_CACHE_GC_ENABLED = _env_bool("PDF_TEXT_CACHE_GC_ENABLED", True)
    PDF_TEXT_CACHE_RETENTION_DAYS = _env_int("PDF_TEXT_CACHE_RETENTION_DAYS", 30)
    OCR_VISION_MIN_SCANNED_PROB = _env_float("OCR_VISION_MIN_SCANNED_PROB", 0.6)

    PARSE_FAILURE_LOGGING_ENABLED = _env_bool("PARSE_FAILURE_LOGGING_ENABLED", True)
    PARSE_FAILURE_LOG_TO_LOGGER = _env_bool("PARSE_FAILURE_LOG_TO_LOGGER", True)
    CASE_STRICT_DATE_VALIDATION = _env_bool("CASE_STRICT_DATE_VALIDATION", True)
    CASE_STRICT_DERIVED_UPDATES = _env_bool("CASE_STRICT_DERIVED_UPDATES", False)
    APP_NO_MIN_MATCH_LENGTH = _env_int("APP_NO_MIN_MATCH_LENGTH", 8)

    ERROR_REPORTING_ENABLED = _env_bool("ERROR_REPORTING_ENABLED", True)
    ERROR_REPORTING_MAX_TEXT = _env_int("ERROR_REPORTING_MAX_TEXT", 20000)
    ERROR_REPORTING_DEDUP_WINDOW_SECONDS = _env_int("ERROR_REPORTING_DEDUP_WINDOW_SECONDS", 2)
    ERROR_REPORT_CAPTURE_LOGGED_EXCEPTIONS = _env_bool(
        "ERROR_REPORT_CAPTURE_LOGGED_EXCEPTIONS", True
    )
    ERROR_REPORT_ALERTS_ENABLED = _env_bool("ERROR_REPORT_ALERTS_ENABLED", False)
    ERROR_REPORT_ALERT_WINDOW_MINUTES = _env_int("ERROR_REPORT_ALERT_WINDOW_MINUTES", 60)
    ERROR_REPORT_ALERT_THRESHOLD = _env_int("ERROR_REPORT_ALERT_THRESHOLD", 10)
    ERROR_REPORT_ALERT_LIMIT = _env_int("ERROR_REPORT_ALERT_LIMIT", 10)
    ERROR_REPORT_ALERT_INTERVAL_MINUTES = _env_int("ERROR_REPORT_ALERT_INTERVAL_MINUTES", 60)
    ERROR_REPORT_ALERT_EMAILS = _env_str("ERROR_REPORT_ALERT_EMAILS", "")
    ERROR_REPORT_ALERT_TOTAL_THRESHOLD = _env_int("ERROR_REPORT_ALERT_TOTAL_THRESHOLD", 0)
    # Disk monitoring
    DISK_SAMPLE_INTERVAL_MINUTES = _env_int("DISK_SAMPLE_INTERVAL_MINUTES", 60)
    DISK_WARN_PCT = _env_float("DISK_WARN_PCT", 80.0)
    DISK_CRIT_PCT = _env_float("DISK_CRIT_PCT", 90.0)
    DISK_MONITOR_ENABLED = _env_bool("DISK_MONITOR_ENABLED", True)
    DISK_MONITOR_PATH = _env_str("DISK_MONITOR_PATH", "")
    DISK_ALERT_THRESHOLD_FREE_PERCENT = _env_float("DISK_ALERT_THRESHOLD_FREE_PERCENT", 10.0)
    DISK_ALERT_COOLDOWN_MINUTES = _env_int("DISK_ALERT_COOLDOWN_MINUTES", 60)
    DISK_ALERT_EMAILS = _env_str("DISK_ALERT_EMAILS", "")
