import os

from app_config.settings.base import BaseSettings, _env_bool, _env_float, _env_int, _env_str


class SchedulerSettings:
    BOOTSTRAP_ENABLED = _env_bool("BOOTSTRAP_ENABLED", True)
    BACKGROUND_WORKERS = _env_int("BACKGROUND_WORKERS", 2)
    BACKGROUND_ALLOW_SYNC_FALLBACK_IN_REQUEST = _env_bool(
        "BACKGROUND_ALLOW_SYNC_FALLBACK_IN_REQUEST", False
    )
    SCHEDULER_ENABLED = _env_bool("SCHEDULER_ENABLED", False)
    SCHEDULER_ADVISORY_LOCK_KEY = _env_int("SCHEDULER_ADVISORY_LOCK_KEY", 915000123)
    SCHEDULER_FILE_LOCK_PATH = _env_str(
        "SCHEDULER_FILE_LOCK_PATH",
        os.path.join(BaseSettings.BASE_DIR, "data", "scheduler.lock"),
    )
    SCHEDULER_LOCK_HEALTHCHECK_SECONDS = _env_int("SCHEDULER_LOCK_HEALTHCHECK_SECONDS", 300)
    SCHEDULER_EXIT_ON_LOCK_LOSS = _env_bool("SCHEDULER_EXIT_ON_LOCK_LOSS", True)
    SCHEDULER_JOB_FAILURE_BACKOFF_ENABLED = _env_bool("SCHEDULER_JOB_FAILURE_BACKOFF_ENABLED", True)
    SCHEDULER_JOB_FAILURE_BACKOFF_BASE_SECONDS = _env_int(
        "SCHEDULER_JOB_FAILURE_BACKOFF_BASE_SECONDS", 60
    )
    SCHEDULER_JOB_FAILURE_BACKOFF_MAX_SECONDS = _env_int(
        "SCHEDULER_JOB_FAILURE_BACKOFF_MAX_SECONDS", 3600
    )
    SCHEDULER_HEARTBEAT_INTERVAL_SECONDS = _env_int("SCHEDULER_HEARTBEAT_INTERVAL_SECONDS", 300)
    SCHEDULER_HEARTBEAT_GRACE_SECONDS = _env_int("SCHEDULER_HEARTBEAT_GRACE_SECONDS", 600)
    SCHEDULER_HEARTBEAT_ENFORCE = _env_bool("SCHEDULER_HEARTBEAT_ENFORCE", False)
    RUN_SCHEDULER = _env_bool("RUN_SCHEDULER", False)

    DEADLINE_AUTO_CLOSE_ENABLED = _env_bool("DEADLINE_AUTO_CLOSE_ENABLED", True)
    DEADLINE_AUTO_CLOSE_HOUR = _env_int("DEADLINE_AUTO_CLOSE_HOUR", 0)
    DEADLINE_AUTO_CLOSE_MINUTE = _env_int("DEADLINE_AUTO_CLOSE_MINUTE", 35)

    OFFICE_ACTION_AUTO_CLOSE_ENABLED = _env_bool("OFFICE_ACTION_AUTO_CLOSE_ENABLED", True)
    OFFICE_ACTION_AUTO_CLOSE_INTERVAL_SECONDS = _env_int(
        "OFFICE_ACTION_AUTO_CLOSE_INTERVAL_SECONDS", 300
    )
    OFFICE_ACTION_AUTO_CLOSE_MATTER_LIMIT = _env_int("OFFICE_ACTION_AUTO_CLOSE_MATTER_LIMIT", 200)

    MATTER_STATUS_RECALC_QUEUE_ENABLED = _env_bool("MATTER_STATUS_RECALC_QUEUE_ENABLED", True)
    MATTER_STATUS_RECALC_QUEUE_INTERVAL_SECONDS = _env_int(
        "MATTER_STATUS_RECALC_QUEUE_INTERVAL_SECONDS", 60
    )
    MATTER_STATUS_RECALC_QUEUE_DRAIN_LIMIT = _env_int(
        "MATTER_STATUS_RECALC_QUEUE_DRAIN_LIMIT", 1000
    )
    MATTER_STATUS_RECALC_QUEUE_MAX_ATTEMPTS = _env_int("MATTER_STATUS_RECALC_QUEUE_MAX_ATTEMPTS", 8)
    MATTER_STATUS_RECALC_QUEUE_BACKOFF_BASE_SECONDS = _env_int(
        "MATTER_STATUS_RECALC_QUEUE_BACKOFF_BASE_SECONDS", 30
    )
    MATTER_STATUS_RECALC_QUEUE_BACKOFF_MAX_SECONDS = _env_int(
        "MATTER_STATUS_RECALC_QUEUE_BACKOFF_MAX_SECONDS", 3600
    )
    MATTER_STATUS_RECALC_QUEUE_LOCK_TIMEOUT_SECONDS = _env_int(
        "MATTER_STATUS_RECALC_QUEUE_LOCK_TIMEOUT_SECONDS", 300
    )

    MATTER_STATUS_CACHE_AUDIT_ENABLED = _env_bool("MATTER_STATUS_CACHE_AUDIT_ENABLED", True)
    MATTER_STATUS_CACHE_AUDIT_INTERVAL_SECONDS = _env_int(
        "MATTER_STATUS_CACHE_AUDIT_INTERVAL_SECONDS", 300
    )
    MATTER_STATUS_CACHE_AUDIT_LIMIT = _env_int("MATTER_STATUS_CACHE_AUDIT_LIMIT", 10000)
    MATTER_STATUS_CACHE_AUDIT_COMMIT_INTERVAL = _env_int(
        "MATTER_STATUS_CACHE_AUDIT_COMMIT_INTERVAL", 250
    )
    MATTER_STATUS_CACHE_AUDIT_CURSOR_KEY = _env_str(
        "MATTER_STATUS_CACHE_AUDIT_CURSOR_KEY",
        "MATTER_STATUS_CACHE_AUDIT_CURSOR",
    )

    MATTER_STATUS_CACHE_RECONCILE_ENABLED = _env_bool(
        "MATTER_STATUS_CACHE_RECONCILE_ENABLED", False
    )
    MATTER_STATUS_CACHE_RECONCILE_HOUR = _env_int("MATTER_STATUS_CACHE_RECONCILE_HOUR", 4)
    MATTER_STATUS_CACHE_RECONCILE_MINUTE = _env_int("MATTER_STATUS_CACHE_RECONCILE_MINUTE", 50)
    MATTER_STATUS_CACHE_RECONCILE_LIMIT = _env_int("MATTER_STATUS_CACHE_RECONCILE_LIMIT", 0)
    MATTER_STATUS_CACHE_RECONCILE_COMMIT_INTERVAL = _env_int(
        "MATTER_STATUS_CACHE_RECONCILE_COMMIT_INTERVAL", 250
    )

    WORKLOG_AUTO_BACKFILL_FROM_DOCKETS_ENABLED = _env_bool(
        "WORKLOG_AUTO_BACKFILL_FROM_DOCKETS_ENABLED",
        True,
    )
    WORKLOG_AUTO_BACKFILL_INTERVAL_SECONDS = _env_int(
        "WORKLOG_AUTO_BACKFILL_INTERVAL_SECONDS", 3600
    )
    WORKLOG_AUTO_BACKFILL_LOOKAHEAD_DAYS = _env_int("WORKLOG_AUTO_BACKFILL_LOOKAHEAD_DAYS", 30)
    WORKLOG_AUTO_BACKFILL_OVERDUE_WINDOW_DAYS = _env_int(
        "WORKLOG_AUTO_BACKFILL_OVERDUE_WINDOW_DAYS", 3650
    )
    WORKLOG_AUTO_BACKFILL_LIMIT = _env_int("WORKLOG_AUTO_BACKFILL_LIMIT", 200)

    HOUSEKEEPING_ENABLED = _env_bool("HOUSEKEEPING_ENABLED", True)
    HOUSEKEEPING_RUN_ON_STARTUP = _env_bool("HOUSEKEEPING_RUN_ON_STARTUP", False)
    HOUSEKEEPING_WARN_WITHOUT_SCHEDULER = _env_bool("HOUSEKEEPING_WARN_WITHOUT_SCHEDULER", True)
    JOB_RUN_RETENTION_DAYS = _env_int("JOB_RUN_RETENTION_DAYS", 90)
    JOB_RUN_SUCCESS_RETENTION_DAYS = _env_int("JOB_RUN_SUCCESS_RETENTION_DAYS", 14)
    JOB_RUN_STALE_MINUTES = _env_int("JOB_RUN_STALE_MINUTES", 720)
    DURABLE_JOB_RETENTION_DAYS = _env_int("DURABLE_JOB_RETENTION_DAYS", 30)
    DURABLE_JOB_FAILED_RETENTION_DAYS = _env_int("DURABLE_JOB_FAILED_RETENTION_DAYS", 180)
    DURABLE_JOB_TASK_RETENTION_DAYS_JSON = _env_str(
        "DURABLE_JOB_TASK_RETENTION_DAYS_JSON",
        "{}",
    )
    ADMIN_JOB_STALE_MINUTES = _env_int("ADMIN_JOB_STALE_MINUTES", 120)
    ADMIN_QUEUE_BACKLOG_WARN_MINUTES = _env_int("ADMIN_QUEUE_BACKLOG_WARN_MINUTES", 60)
    USER_ACCESS_LOG_RETENTION_DAYS = _env_int("USER_ACCESS_LOG_RETENTION_DAYS", 90)
    DISK_SAMPLE_RETENTION_DAYS = _env_int("DISK_SAMPLE_RETENTION_DAYS", 180)
    OPERATIONAL_TABLE_WARN_MB = _env_int("OPERATIONAL_TABLE_WARN_MB", 0)
    OPERATIONAL_TABLE_WARN_ROWS = _env_int("OPERATIONAL_TABLE_WARN_ROWS", 0)
    OPERATIONAL_TABLE_WARN_ROWS_24H = _env_int("OPERATIONAL_TABLE_WARN_ROWS_24H", 0)
    OPERATIONAL_TABLE_EXPIRED_WARN_ROWS = _env_int("OPERATIONAL_TABLE_EXPIRED_WARN_ROWS", 1000)
    OPERATIONAL_TABLE_JOB_RUNS_WARN_MB = _env_int("OPERATIONAL_TABLE_JOB_RUNS_WARN_MB", 0)
    OPERATIONAL_TABLE_JOB_RUNS_WARN_ROWS = _env_int("OPERATIONAL_TABLE_JOB_RUNS_WARN_ROWS", 0)
    OPERATIONAL_TABLE_JOB_RUNS_WARN_ROWS_24H = _env_int(
        "OPERATIONAL_TABLE_JOB_RUNS_WARN_ROWS_24H", 0
    )
    OPERATIONAL_TABLE_USER_ACCESS_LOG_WARN_MB = _env_int(
        "OPERATIONAL_TABLE_USER_ACCESS_LOG_WARN_MB", 0
    )
    OPERATIONAL_TABLE_USER_ACCESS_LOG_WARN_ROWS = _env_int(
        "OPERATIONAL_TABLE_USER_ACCESS_LOG_WARN_ROWS", 0
    )
    OPERATIONAL_TABLE_USER_ACCESS_LOG_WARN_ROWS_24H = _env_int(
        "OPERATIONAL_TABLE_USER_ACCESS_LOG_WARN_ROWS_24H", 0
    )
    OPERATIONAL_TABLE_DURABLE_JOBS_WARN_MB = _env_int("OPERATIONAL_TABLE_DURABLE_JOBS_WARN_MB", 0)
    OPERATIONAL_TABLE_DURABLE_JOBS_WARN_ROWS = _env_int(
        "OPERATIONAL_TABLE_DURABLE_JOBS_WARN_ROWS", 0
    )
    OPERATIONAL_TABLE_DURABLE_JOBS_WARN_ROWS_24H = _env_int(
        "OPERATIONAL_TABLE_DURABLE_JOBS_WARN_ROWS_24H", 0
    )

    DEFERRED_TASKS_DURABLE_QUEUE_ENABLED = _env_bool(
        "DEFERRED_TASKS_DURABLE_QUEUE_ENABLED",
        True,
    )
    DURABLE_QUEUE_POLL_SECONDS = _env_float("DURABLE_QUEUE_POLL_SECONDS", 2.0)
    DURABLE_QUEUE_LOCK_TTL_SECONDS = _env_int("DURABLE_QUEUE_LOCK_TTL_SECONDS", 600)
    DURABLE_QUEUE_MAX_BACKOFF_SECONDS = _env_int("DURABLE_QUEUE_MAX_BACKOFF_SECONDS", 3600)
    WORKER_HEARTBEAT_RETENTION_DAYS = _env_int("WORKER_HEARTBEAT_RETENTION_DAYS", 7)
