from __future__ import annotations

from app.models.permissions import Permissions


def get_default_role_profiles() -> dict[str, list[str]]:
    """Return the baseline permission set for built-in roles."""
    return {
        "user": [],
        "admin": [key for key, _ in Permissions.all_permissions()],
        "mgmt_director": [
            Permissions.MENU_CASES,
            Permissions.MENU_DEADLINES,
            Permissions.MENU_NOTICES,
            Permissions.MENU_RENEWAL,
            Permissions.MENU_CRM,
            Permissions.MENU_ACCOUNTING,
            Permissions.MENU_STATISTICS,
            Permissions.MENU_MGMT,
            Permissions.CASE_VIEW_ALL,
            Permissions.CASE_EDIT_ALL,
            Permissions.CASE_DELETE,
            Permissions.INVOICE_MANAGE,
        ],
        "lead_attorney": [
            Permissions.MENU_CASES,
            Permissions.MENU_DEADLINES,
            Permissions.MENU_NOTICES,
            Permissions.MENU_RENEWAL,
            Permissions.MENU_CRM,
            Permissions.MENU_ACCOUNTING,
            Permissions.MENU_STATISTICS,
            Permissions.MENU_MGMT,
            Permissions.CASE_VIEW_ALL,
            Permissions.CASE_EDIT_ALL,
            Permissions.CASE_ASSIGN_ALL,
            Permissions.CASE_DELETE,
            Permissions.INVOICE_MANAGE,
        ],
        "partner_attorney": [
            Permissions.MENU_CASES,
            Permissions.MENU_DEADLINES,
            Permissions.MENU_NOTICES,
            Permissions.MENU_RENEWAL,
            Permissions.MENU_CRM,
            Permissions.MENU_ACCOUNTING,
            Permissions.MENU_STATISTICS,
            Permissions.MENU_MGMT,
            Permissions.CASE_VIEW_ALL,
            Permissions.CASE_EDIT_ALL,
            Permissions.CASE_ASSIGN_ALL,
            Permissions.CASE_DELETE,
            Permissions.INVOICE_MANAGE,
        ],
        "mgmt_staff": [
            Permissions.MENU_CASES,
            Permissions.MENU_DEADLINES,
            Permissions.MENU_NOTICES,
            Permissions.MENU_RENEWAL,
            Permissions.MENU_CRM,
            Permissions.MENU_ACCOUNTING,
            Permissions.CASE_VIEW_ALL,
            Permissions.CASE_VIEW_ASSIGNED,
            Permissions.CASE_VIEW_TEAM,
            Permissions.CASE_EDIT_ASSIGNED,
            Permissions.CASE_EDIT_ALL,
            Permissions.CASE_ASSIGN_TEAM,
            Permissions.CASE_ASSIGN_ALL,
        ],
        "patent_staff": [
            Permissions.MENU_CASES,
            Permissions.MENU_DEADLINES,
            Permissions.MENU_NOTICES,
            Permissions.MENU_RENEWAL,
            Permissions.MENU_CRM,
            Permissions.MENU_ACCOUNTING,
            Permissions.CASE_VIEW_ASSIGNED,
            Permissions.CASE_VIEW_TEAM,
            Permissions.CASE_EDIT_ASSIGNED,
            Permissions.CASE_EDIT_TEAM,
        ],
    }
